# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/zidir/Desktop/labo2-2429561-2433385/project_2/project_2.srcs/sources_1/bd/zynq/ip/zynq_ps7_0_axi_periph_imp_auto_pc_0/zynq_ps7_0_axi_periph_imp_auto_pc_0.xci
# IP: The module: 'zynq_ps7_0_axi_periph_imp_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/zidir/Desktop/labo2-2429561-2433385/project_2/project_2.gen/sources_1/bd/zynq/ip/zynq_ps7_0_axi_periph_imp_auto_pc_0/zynq_ps7_0_axi_periph_imp_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_ps7_0_axi_periph_imp_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/zidir/Desktop/labo2-2429561-2433385/project_2/project_2.srcs/sources_1/bd/zynq/ip/zynq_ps7_0_axi_periph_imp_auto_pc_0/zynq_ps7_0_axi_periph_imp_auto_pc_0.xci
# IP: The module: 'zynq_ps7_0_axi_periph_imp_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/zidir/Desktop/labo2-2429561-2433385/project_2/project_2.gen/sources_1/bd/zynq/ip/zynq_ps7_0_axi_periph_imp_auto_pc_0/zynq_ps7_0_axi_periph_imp_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_ps7_0_axi_periph_imp_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
