# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/zidir/Desktop/lemside/3500/labo2-2429561-2433385/xdc/PYNQ-Z2-v1.0.xdc

# Block Designs: bd/zynq/zynq.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq || ORIG_REF_NAME==zynq} -quiet] -quiet

# IP: bd/zynq/ip/zynq_axi_gpio_0_0/zynq_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_axi_gpio_0_0 || ORIG_REF_NAME==zynq_axi_gpio_0_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_proc_sys_reset_0_0/zynq_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_proc_sys_reset_0_0 || ORIG_REF_NAME==zynq_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_processing_system7_0_0/zynq_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_processing_system7_0_0 || ORIG_REF_NAME==zynq_processing_system7_0_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_ps7_0_axi_periph_imp_auto_pc_0/zynq_ps7_0_axi_periph_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_ps7_0_axi_periph_imp_auto_pc_0 || ORIG_REF_NAME==zynq_ps7_0_axi_periph_imp_auto_pc_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_ps7_0_axi_periph_0/zynq_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_ps7_0_axi_periph_0 || ORIG_REF_NAME==zynq_ps7_0_axi_periph_0} -quiet] -quiet

# XDC: c:/Users/zidir/Desktop/lemside/3500/labo2-2429561-2433385/project_2/project_2.gen/sources_1/bd/zynq/zynq_ooc.xdc
